sonar.projectKey=aashishchaudhari_devsecops-challenge
sonar.organization=aashishchaudhari
sonar.projectName=devsecops-challenge
sonar.sources=.
sonar.exclusions=venv/**,**/__pycache__/**
sonar.host.url=https://sonarcloud.io
