sonar.projectKey=AashishChaudhari_devsecops-challenge
sonar.organization=AashishChaudhari
sonar.projectName=devsecops-challenge
sonar.sources=.
sonar.exclusions=venv/**,**/__pycache__/**
sonar.host.url=https://sonarcloud.io
